### ISSUE TITLE
Don't Require LineIcons

### ISSUE THREAD

**Issue by sshaw** [brookesb91/dismissible#8]
One of the great things about this library is its size. Unfortunately it depends on LineIcons, whose CSS is larger that both this library's CSS _and_ JS. 

One can exclude LineIcons but then the `X` to close the banner is not visible. One must then add something like: 

```css
.lni-close::after {
    content: 'X';
}
```

I would be great to have defaults that don't require an external library.
